//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeMendez.UI.dataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoritos
    {
        public int FavoritoID { get; set; }
        public int UsuarioID { get; set; }
        public int ProductoID { get; set; }
        public Nullable<System.DateTime> FechaAgregado { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
